export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILTURE = "USER_LOGIN_FAILTURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_DISCONNECTED = "SOCKET_DISCONNECTED";

export const API_REQUEST = "API_REQUEST";
export const API_REQUEST_SUCCESS = "API_REQUEST_SUCCESS";
export const API_REQUEST_FAILTURE = "API_REQUEST_FAILTURE";

export const CHANGE_APP_MODE = "CHANGE_APP_MODE";
