export const WORLD_ENTER = "WORLD_ENTER";
export const WORLD_RETURN = "WORLD_RETURN";
export const WORLD_TEXT_DISPLAY = "WORLD_TEXT_DISPLAY";
export const WORLD_TEXT_CLEAR = "WORLD_TEXT_CLEAR";
export const WORLD_EXIT = "WORLD_EXIT";
